services:
  heimdall:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: heimdall-dev
    ports:
      - "8080:8080"
    volumes:
      - ../:/var/www/html
      - heimdall_vendor:/var/www/html/vendor
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      PHP_CLI_SERVER_WORKERS: 4

volumes:
  heimdall_vendor:
